# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-devops

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'nginx-alpine'
  AQUA_URL: 'http://34.75.241.250:8080'
  AQUA_USER: 'scanner'
  AQUA_REG: 'ACR'
  TIMEOUT: '60'
  AQUA_IMAGE_NAME: 'nginx:1.17.1-alpine'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'aquaken'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
- task: Bash@3
  inputs:
    filePath: 'scan-new-image.sh'
    arguments: '$AQUA_URL $AQUA_REG $(imageName):$(Build.BuildId)'
  displayName: 'Scan an image using the Aqua API.'
- task: Bash@3
  inputs:
    filePath: 'scan-check-queue-status.sh'
    arguments: '$AQUA_URL $AQUA_REG $(imageName):$(Build.BuildId)'
  displayName: 'Check and poll for scan result.'